'use client'

import { useState, useReducer, ReactNode } from 'react'
import { ChevronLeft, ChevronRight, Download, Mail, RotateCcw } from 'lucide-react'

// Types
interface FormData {
  // Step 1: Goals
  goals: string[]

  // Step 2: Basic Profile
  age?: number
  biologicalSex?: string
  weight?: number
  weightUnit?: 'lbs' | 'kg'
  activityLevel?: string
  conditions?: string

  // Step 3: Advanced Data
  bloodwork?: {
    fastingInsulin?: number
    igf1?: number
    crp?: number
    testosterone?: number
    estradiol?: number
    freeT3?: number
    tsh?: number
    fastingGlucose?: number
    hba1c?: number
    vitaminD?: number
  }
  supplements?: string
  geneticVariants?: string
  healthHistory?: string

  // Step 4: Email + Generate
  email?: string
}

interface ProtocolResult {
  title: string
  summary: string
  sections: Array<{
    heading: string
    content: string
    subsections?: Array<{
      title: string
      content: string
    }>
  }>
  disclaimer: string
}

type WizardStep = 'disclaimer' | 'goals' | 'profile' | 'advanced' | 'email' | 'loading' | 'results'

interface WizardState {
  currentStep: WizardStep
  formData: FormData
  protocol?: ProtocolResult
  error?: string
}

type WizardAction =
  | { type: 'SET_STEP'; payload: WizardStep }
  | { type: 'UPDATE_FORM'; payload: Partial<FormData> }
  | { type: 'SET_PROTOCOL'; payload: ProtocolResult }
  | { type: 'SET_ERROR'; payload: string }
  | { type: 'RESET' }

const initialState: WizardState = {
  currentStep: 'disclaimer',
  formData: {
    goals: [],
    weightUnit: 'lbs',
    bloodwork: {},
  },
}

function wizardReducer(state: WizardState, action: WizardAction): WizardState {
  switch (action.type) {
    case 'SET_STEP':
      return { ...state, currentStep: action.payload, error: undefined }
    case 'UPDATE_FORM':
      return {
        ...state,
        formData: { ...state.formData, ...action.payload },
      }
    case 'SET_PROTOCOL':
      return { ...state, protocol: action.payload }
    case 'SET_ERROR':
      return { ...state, error: action.payload }
    case 'RESET':
      return initialState
    default:
      return state
  }
}

const GOAL_OPTIONS = [
  'Fat Loss',
  'Muscle Growth',
  'Gut Health',
  'Anti-Inflammation',
  'Longevity/Anti-Aging',
  'Cognitive Performance',
  'Sleep Quality',
  'Injury Recovery',
  'Hormone Optimization',
  'Energy/Mitochondrial Health',
  'Skin/Hair',
  'Immune Support',
]

const ACTIVITY_LEVELS = [
  'Sedentary',
  'Lightly Active',
  'Moderately Active',
  'Very Active',
  'Athlete',
]

// Step Components
function DisclaimerStep({
  onNext,
}: {
  onNext: () => void
}): ReactNode {
  const [agreed, setAgreed] = useState(false)

  return (
    <div className="animate-fade-in-up space-y-6">
      <div>
        <h2 className="heading-section mb-4">Important Disclaimer</h2>
        <div className="space-y-4 text-body">
          <p>
            Welcome to the Peptide Protocols Personalization Wizard. Before we
            begin, please read the following important information:
          </p>

          <div className="rounded-lg bg-sand-50 p-4 border border-sand-200">
            <h3 className="font-semibold text-warm-900 mb-2">
              Educational Purposes Only
            </h3>
            <p className="text-sm text-warm-800">
              The protocols generated by this tool are educational in nature and
              are not medical advice, diagnoses, or treatment recommendations.
              This tool does not establish a doctor-patient relationship.
            </p>
          </div>

          <div className="rounded-lg bg-sand-50 p-4 border border-sand-200">
            <h3 className="font-semibold text-warm-900 mb-2">
              Consult Healthcare Providers
            </h3>
            <p className="text-sm text-warm-800">
              Before starting any new protocol or making changes to your current
              health regimen, you must consult with a qualified healthcare
              provider. Results are highly individual and depend on many
              factors.
            </p>
          </div>

          <div className="rounded-lg bg-sand-50 p-4 border border-sand-200">
            <h3 className="font-semibold text-warm-900 mb-2">
              Not a Substitute for Professional Medical Advice
            </h3>
            <p className="text-sm text-warm-800">
              This tool is educational and should not replace professional
              medical advice, examination, diagnosis, or treatment by a
              qualified healthcare provider.
            </p>
          </div>

          <div className="rounded-lg bg-sand-50 p-4 border border-sand-200">
            <h3 className="font-semibold text-warm-900 mb-2">
              Data Privacy
            </h3>
            <p className="text-sm text-warm-800">
              Your health information is processed in real-time and never
              permanently stored. We do not share your data with third parties.
            </p>
          </div>
        </div>
      </div>

      <div className="flex items-start gap-3">
        <input
          type="checkbox"
          id="agree"
          checked={agreed}
          onChange={(e) => setAgreed(e.target.checked)}
          className="mt-1 h-5 w-5 rounded border-warm-300 text-sage-600 cursor-pointer accent-sage-600"
        />
        <label htmlFor="agree" className="text-sm text-warm-800 cursor-pointer">
          I understand that this is educational content, not medical advice, and
          I will consult with a healthcare provider before implementing any
          protocol.
        </label>
      </div>

      <button
        onClick={onNext}
        disabled={!agreed}
        className="btn-primary disabled:opacity-50 disabled:cursor-not-allowed w-full sm:w-auto"
      >
        I Agree & Continue
      </button>
    </div>
  )
}

function GoalsStep({
  goals,
  onUpdate,
  onNext,
}: {
  goals: string[]
  onUpdate: (goals: string[]) => void
  onNext: () => void
}): ReactNode {
  const toggleGoal = (goal: string) => {
    if (goals.includes(goal)) {
      onUpdate(goals.filter((g) => g !== goal))
    } else {
      onUpdate([...goals, goal])
    }
  }

  return (
    <div className="animate-fade-in-up space-y-6">
      <div>
        <h2 className="heading-section mb-2">What Are Your Goals?</h2>
        <p className="text-body text-warm-700">
          Select at least one goal. You can choose multiple.
        </p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        {GOAL_OPTIONS.map((goal) => (
          <button
            key={goal}
            onClick={() => toggleGoal(goal)}
            className={`px-4 py-3 rounded-full text-sm font-medium transition-all duration-200 border-2 ${
              goals.includes(goal)
                ? 'bg-sage-600 text-white border-sage-600'
                : 'bg-white text-warm-800 border-warm-200 hover:border-sage-300'
            }`}
          >
            {goal}
          </button>
        ))}
      </div>

      {goals.length === 0 && (
        <div className="rounded-lg bg-sand-50 p-4 border border-sand-200 text-sm text-warm-700">
          Please select at least one goal to continue.
        </div>
      )}

      <button
        onClick={onNext}
        disabled={goals.length === 0}
        className="btn-primary disabled:opacity-50 disabled:cursor-not-allowed w-full sm:w-auto"
      >
        Next: Profile
      </button>
    </div>
  )
}

function ProfileStep({
  formData,
  onUpdate,
  onNext,
  onSkip,
}: {
  formData: FormData
  onUpdate: (data: Partial<FormData>) => void
  onNext: () => void
  onSkip: () => void
}): ReactNode {
  return (
    <div className="animate-fade-in-up space-y-6">
      <div>
        <h2 className="heading-section mb-2">Basic Profile</h2>
        <p className="text-body text-warm-700">
          This information helps personalize your protocol. You can skip this
          step if you prefer.
        </p>
      </div>

      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-warm-900 mb-2">
            Age
          </label>
          <input
            type="number"
            min="18"
            max="120"
            value={formData.age || ''}
            onChange={(e) =>
              onUpdate({ age: e.target.value ? parseInt(e.target.value) : undefined })
            }
            placeholder="e.g., 35"
            className="w-full px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 placeholder-warm-500 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-warm-900 mb-2">
            Biological Sex
          </label>
          <select
            value={formData.biologicalSex || ''}
            onChange={(e) => onUpdate({ biologicalSex: e.target.value })}
            className="w-full px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all"
          >
            <option value="">Select...</option>
            <option value="Male">Male</option>
            <option value="Female">Female</option>
            <option value="Other">Prefer not to say</option>
          </select>
        </div>

        <div>
          <label className="block text-sm font-medium text-warm-900 mb-2">
            Weight
          </label>
          <div className="flex gap-3">
            <input
              type="number"
              min="0"
              max="500"
              step="0.1"
              value={formData.weight || ''}
              onChange={(e) =>
                onUpdate({
                  weight: e.target.value ? parseFloat(e.target.value) : undefined,
                })
              }
              placeholder="e.g., 175"
              className="flex-1 px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 placeholder-warm-500 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all"
            />
            <select
              value={formData.weightUnit || 'lbs'}
              onChange={(e) =>
                onUpdate({ weightUnit: e.target.value as 'lbs' | 'kg' })
              }
              className="px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all"
            >
              <option value="lbs">lbs</option>
              <option value="kg">kg</option>
            </select>
          </div>
        </div>

        <div>
          <label className="block text-sm font-medium text-warm-900 mb-2">
            Activity Level
          </label>
          <select
            value={formData.activityLevel || ''}
            onChange={(e) => onUpdate({ activityLevel: e.target.value })}
            className="w-full px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all"
          >
            <option value="">Select...</option>
            {ACTIVITY_LEVELS.map((level) => (
              <option key={level} value={level}>
                {level}
              </option>
            ))}
          </select>
        </div>

        <div>
          <label className="block text-sm font-medium text-warm-900 mb-2">
            Current Medications or Conditions
          </label>
          <textarea
            value={formData.conditions || ''}
            onChange={(e) => onUpdate({ conditions: e.target.value })}
            placeholder="e.g., Hypertension managed with lisinopril, no allergies..."
            rows={3}
            className="w-full px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 placeholder-warm-500 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all resize-none"
          />
        </div>
      </div>

      <div className="flex gap-3 flex-wrap">
        <button
          onClick={onNext}
          className="btn-primary"
        >
          Next: Advanced Data
        </button>
        <button
          onClick={onSkip}
          className="btn-secondary"
        >
          Skip This Step
        </button>
      </div>
    </div>
  )
}

function AdvancedStep({
  formData,
  onUpdate,
  onNext,
  onSkip,
}: {
  formData: FormData
  onUpdate: (data: Partial<FormData>) => void
  onNext: () => void
  onSkip: () => void
}): ReactNode {
  const bloodwork = formData.bloodwork || {}

  const updateBloodwork = (key: string, value: number | undefined) => {
    onUpdate({
      bloodwork: {
        ...bloodwork,
        [key]: value,
      },
    })
  }

  return (
    <div className="animate-fade-in-up space-y-6">
      <div>
        <h2 className="heading-section mb-2">Advanced Health Data</h2>
        <p className="text-body text-warm-700">
          Optional: Include your bloodwork and genetic data for more precise
          recommendations. All fields are optional.
        </p>
      </div>

      <div className="space-y-6">
        <div>
          <h3 className="font-semibold text-warm-900 mb-4">Bloodwork Values</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-warm-900 mb-2">
                Fasting Insulin (μIU/mL)
              </label>
              <input
                type="number"
                step="0.1"
                value={bloodwork.fastingInsulin || ''}
                onChange={(e) =>
                  updateBloodwork(
                    'fastingInsulin',
                    e.target.value ? parseFloat(e.target.value) : undefined
                  )
                }
                placeholder="e.g., 3.2"
                className="w-full px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 placeholder-warm-500 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-warm-900 mb-2">
                IGF-1 (ng/mL)
              </label>
              <input
                type="number"
                step="1"
                value={bloodwork.igf1 || ''}
                onChange={(e) =>
                  updateBloodwork('igf1', e.target.value ? parseFloat(e.target.value) : undefined)
                }
                placeholder="e.g., 220"
                className="w-full px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 placeholder-warm-500 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-warm-900 mb-2">
                CRP/hs-CRP (mg/L)
              </label>
              <input
                type="number"
                step="0.1"
                value={bloodwork.crp || ''}
                onChange={(e) =>
                  updateBloodwork('crp', e.target.value ? parseFloat(e.target.value) : undefined)
                }
                placeholder="e.g., 0.8"
                className="w-full px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 placeholder-warm-500 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-warm-900 mb-2">
                Testosterone (Total) (ng/dL)
              </label>
              <input
                type="number"
                step="1"
                value={bloodwork.testosterone || ''}
                onChange={(e) =>
                  updateBloodwork(
                    'testosterone',
                    e.target.value ? parseFloat(e.target.value) : undefined
                  )
                }
                placeholder="e.g., 650"
                className="w-full px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 placeholder-warm-500 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-warm-900 mb-2">
                Estradiol (pg/mL)
              </label>
              <input
                type="number"
                step="0.1"
                value={bloodwork.estradiol || ''}
                onChange={(e) =>
                  updateBloodwork(
                    'estradiol',
                    e.target.value ? parseFloat(e.target.value) : undefined
                  )
                }
                placeholder="e.g., 25"
                className="w-full px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 placeholder-warm-500 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-warm-900 mb-2">
                Free T3 (pg/mL)
              </label>
              <input
                type="number"
                step="0.1"
                value={bloodwork.freeT3 || ''}
                onChange={(e) =>
                  updateBloodwork(
                    'freeT3',
                    e.target.value ? parseFloat(e.target.value) : undefined
                  )
                }
                placeholder="e.g., 3.4"
                className="w-full px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 placeholder-warm-500 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-warm-900 mb-2">
                TSH (mIU/L)
              </label>
              <input
                type="number"
                step="0.01"
                value={bloodwork.tsh || ''}
                onChange={(e) =>
                  updateBloodwork('tsh', e.target.value ? parseFloat(e.target.value) : undefined)
                }
                placeholder="e.g., 1.5"
                className="w-full px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 placeholder-warm-500 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-warm-900 mb-2">
                Fasting Glucose (mg/dL)
              </label>
              <input
                type="number"
                step="1"
                value={bloodwork.fastingGlucose || ''}
                onChange={(e) =>
                  updateBloodwork(
                    'fastingGlucose',
                    e.target.value ? parseFloat(e.target.value) : undefined
                  )
                }
                placeholder="e.g., 92"
                className="w-full px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 placeholder-warm-500 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-warm-900 mb-2">
                HbA1c (%)
              </label>
              <input
                type="number"
                step="0.1"
                value={bloodwork.hba1c || ''}
                onChange={(e) =>
                  updateBloodwork(
                    'hba1c',
                    e.target.value ? parseFloat(e.target.value) : undefined
                  )
                }
                placeholder="e.g., 5.1"
                className="w-full px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 placeholder-warm-500 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-warm-900 mb-2">
                Vitamin D (ng/mL)
              </label>
              <input
                type="number"
                step="1"
                value={bloodwork.vitaminD || ''}
                onChange={(e) =>
                  updateBloodwork(
                    'vitaminD',
                    e.target.value ? parseFloat(e.target.value) : undefined
                  )
                }
                placeholder="e.g., 55"
                className="w-full px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 placeholder-warm-500 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all"
              />
            </div>
          </div>
        </div>

        <div>
          <label className="block text-sm font-medium text-warm-900 mb-2">
            Current Supplements/Peptides
          </label>
          <textarea
            value={formData.supplements || ''}
            onChange={(e) => onUpdate({ supplements: e.target.value })}
            placeholder="e.g., Omega-3 fish oil, Magnesium glycinate, BPC-157 500mcg daily..."
            rows={3}
            className="w-full px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 placeholder-warm-500 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all resize-none"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-warm-900 mb-2">
            Known Genetic Variants
          </label>
          <textarea
            value={formData.geneticVariants || ''}
            onChange={(e) => onUpdate({ geneticVariants: e.target.value })}
            placeholder="e.g., MTHFR C677T heterozygous, COMT V158M..."
            rows={2}
            className="w-full px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 placeholder-warm-500 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all resize-none"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-warm-900 mb-2">
            Health History Notes
          </label>
          <textarea
            value={formData.healthHistory || ''}
            onChange={(e) => onUpdate({ healthHistory: e.target.value })}
            placeholder="e.g., History of autoimmune issues, family history of diabetes..."
            rows={2}
            className="w-full px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 placeholder-warm-500 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all resize-none"
          />
        </div>
      </div>

      <div className="flex gap-3 flex-wrap">
        <button
          onClick={onNext}
          className="btn-primary"
        >
          Next: Email & Generate
        </button>
        <button
          onClick={onSkip}
          className="btn-secondary"
        >
          Skip This Step
        </button>
      </div>
    </div>
  )
}

function EmailStep({
  formData,
  onUpdate,
  onNext,
  onGenerate,
  isLoading,
}: {
  formData: FormData
  onUpdate: (data: Partial<FormData>) => void
  onNext: () => void
  onGenerate: () => void
  isLoading: boolean
}): ReactNode {
  const [expanded, setExpanded] = useState(false)

  const canGenerate = formData.email && formData.goals.length > 0

  return (
    <div className="animate-fade-in-up space-y-6">
      <div>
        <h2 className="heading-section mb-2">Email & Generate</h2>
        <p className="text-body text-warm-700">
          Enter your email to receive your personalized protocol.
        </p>
      </div>

      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-warm-900 mb-2">
            Email Address <span className="text-sage-600">*</span>
          </label>
          <input
            type="email"
            value={formData.email || ''}
            onChange={(e) => onUpdate({ email: e.target.value })}
            placeholder="your@email.com"
            className="w-full px-4 py-2.5 rounded-lg border border-warm-300 bg-white text-warm-900 placeholder-warm-500 focus:outline-none focus:ring-2 focus:ring-sage-500 focus:border-transparent transition-all"
          />
          <p className="text-xs text-warm-700 mt-2">
            Your health data is processed in real-time and never permanently stored.
          </p>
        </div>

        <div className="bg-sand-50 p-4 rounded-lg border border-sand-200">
          <button
            onClick={() => setExpanded(!expanded)}
            className="flex items-center gap-2 text-sm font-medium text-warm-900 hover:text-sage-700 transition-colors"
          >
            <span>{expanded ? '−' : '+'}</span>
            Review Your Information
          </button>
          {expanded && (
            <div className="mt-4 space-y-3 text-sm text-warm-800">
              <div>
                <span className="font-medium">Goals:</span>{' '}
                {formData.goals.length > 0
                  ? formData.goals.join(', ')
                  : 'None selected'}
              </div>
              {formData.age && (
                <div>
                  <span className="font-medium">Age:</span> {formData.age}
                </div>
              )}
              {formData.weight && (
                <div>
                  <span className="font-medium">Weight:</span> {formData.weight}{' '}
                  {formData.weightUnit}
                </div>
              )}
              {formData.biologicalSex && (
                <div>
                  <span className="font-medium">Sex:</span> {formData.biologicalSex}
                </div>
              )}
              {formData.activityLevel && (
                <div>
                  <span className="font-medium">Activity Level:</span>{' '}
                  {formData.activityLevel}
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      <button
        onClick={() => {
          onNext()
          onGenerate()
        }}
        disabled={!canGenerate || isLoading}
        className="btn-primary disabled:opacity-50 disabled:cursor-not-allowed w-full sm:w-auto"
      >
        {isLoading ? 'Generating...' : 'Generate My Protocol'}
      </button>
    </div>
  )
}

function LoadingStep(): ReactNode {
  const steps = [
    'Analyzing your goals...',
    'Matching compounds...',
    'Building dosing schedule...',
    'Generating protocol...',
  ]

  return (
    <div className="animate-fade-in-up space-y-6 text-center py-12">
      <div className="inline-block">
        <div className="w-12 h-12 border-4 border-sage-200 border-t-sage-600 rounded-full animate-spin mx-auto"></div>
      </div>

      <div>
        <h2 className="heading-section mb-4">
          Our AI is analyzing your profile...
        </h2>
        <p className="text-body text-warm-700 mb-6">
          Building your personalized protocol based on your unique goals and health
          data.
        </p>
      </div>

      <div className="space-y-2">
        {steps.map((step, index) => (
          <div
            key={step}
            className="text-sm text-warm-700 animate-fade-in-up"
            style={{ animationDelay: `${index * 0.2}s` }}
          >
            <span className="inline-block w-2 h-2 rounded-full bg-sage-600 mr-2"></span>
            {step}
          </div>
        ))}
      </div>
    </div>
  )
}

function ResultsStep({
  protocol,
  email,
  onReset,
}: {
  protocol: ProtocolResult
  email: string
  onReset: () => void
}): ReactNode {
  const [emailSent, setEmailSent] = useState(false)
  const [isSending, setIsSending] = useState(false)
  const [downloadError, setDownloadError] = useState<string>('')

  const handleDownloadPDF = async () => {
    try {
      setDownloadError('')
      const response = await fetch('/api/generate-pdf', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ protocol }),
      })

      if (!response.ok) {
        throw new Error('Failed to generate PDF')
      }

      const blob = await response.blob()
      const url = window.URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = 'personalized-protocol.pdf'
      document.body.appendChild(a)
      a.click()
      window.URL.revokeObjectURL(url)
      document.body.removeChild(a)
    } catch (error) {
      setDownloadError('Failed to download PDF. Please try again.')
      console.error('PDF download error:', error)
    }
  }

  const handleSendEmail = async () => {
    try {
      setEmailSent(false)
      setIsSending(true)
      const response = await fetch('/api/send-protocol-email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, protocol }),
      })

      if (!response.ok) {
        throw new Error('Failed to send email')
      }

      setEmailSent(true)
      setTimeout(() => setEmailSent(false), 5000)
    } catch (error) {
      console.error('Email send error:', error)
    } finally {
      setIsSending(false)
    }
  }

  return (
    <div className="animate-fade-in-up space-y-8">
      <div className="text-center">
        <div className="inline-flex items-center justify-center w-12 h-12 rounded-full bg-sage-100 mb-4">
          <div className="w-6 h-6 rounded-full border-2 border-sage-600 border-t-transparent"></div>
        </div>
        <h2 className="heading-section mb-2">Your Protocol is Ready</h2>
        <p className="text-body text-warm-700">
          Here's your personalized peptide protocol based on your unique profile.
        </p>
      </div>

      <div className="bg-white rounded-2xl border border-warm-200 p-6 sm:p-8 space-y-6">
        <div>
          <h3 className="font-display text-2xl font-medium text-warm-900 mb-2">
            {protocol.title}
          </h3>
          <p className="text-body text-warm-700">{protocol.summary}</p>
        </div>

        <div className="space-y-6 border-t border-warm-200 pt-6">
          {protocol.sections.map((section, idx) => (
            <div key={idx} className="space-y-3">
              <h4 className="font-semibold text-warm-900 text-lg">
                {section.heading}
              </h4>
              <div
                className="text-body text-warm-800 space-y-2"
                dangerouslySetInnerHTML={{ __html: section.content }}
              />
              {section.subsections && section.subsections.length > 0 && (
                <div className="space-y-3 ml-4 border-l-2 border-sage-200 pl-4">
                  {section.subsections.map((sub, subIdx) => (
                    <div key={subIdx}>
                      <h5 className="font-medium text-warm-900">
                        {sub.title}
                      </h5>
                      <div
                        className="text-sm text-warm-800 mt-1"
                        dangerouslySetInnerHTML={{ __html: sub.content }}
                      />
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>

        <div className="rounded-lg bg-sand-50 p-4 border border-sand-200 text-sm text-warm-700">
          <p className="font-semibold text-warm-900 mb-2">Important Reminder</p>
          {protocol.disclaimer}
        </div>
      </div>

      <div className="space-y-3">
        {downloadError && (
          <div className="p-3 rounded-lg bg-red-50 text-red-700 text-sm">
            {downloadError}
          </div>
        )}

        {emailSent && (
          <div className="p-3 rounded-lg bg-sage-50 text-sage-700 text-sm">
            Protocol sent to {email}!
          </div>
        )}

        <div className="flex flex-col sm:flex-row gap-3">
          <button
            onClick={handleDownloadPDF}
            className="btn-primary inline-flex items-center justify-center gap-2"
          >
            <Download size={16} />
            Download PDF
          </button>

          <button
            onClick={handleSendEmail}
            disabled={isSending}
            className="btn-secondary inline-flex items-center justify-center gap-2 disabled:opacity-50"
          >
            <Mail size={16} />
            {isSending ? 'Sending...' : 'Email Me This'}
          </button>

          <button
            onClick={onReset}
            className="btn-secondary inline-flex items-center justify-center gap-2"
          >
            <RotateCcw size={16} />
            Start Over
          </button>
        </div>
      </div>
    </div>
  )
}

// Main Wizard Component
export default function ProtocolWizard() {
  const [state, dispatch] = useReducer(wizardReducer, initialState)
  const [consentGiven, setConsentGiven] = useState(false)

  const stepIndex = {
    disclaimer: 0,
    goals: 1,
    profile: 2,
    advanced: 3,
    email: 4,
    loading: 5,
    results: 6,
  }

  const currentStepIndex = stepIndex[state.currentStep]
  const totalSteps = 6 // Not counting results as a "step" in progress

  const goToStep = (step: WizardStep) => {
    dispatch({ type: 'SET_STEP', payload: step })
  }

  const handleDisclaimerNext = () => {
    setConsentGiven(true)
    goToStep('goals')
  }

  const handleGoalsNext = () => {
    goToStep('profile')
  }

  const handleProfileNext = () => {
    goToStep('advanced')
  }

  const handleProfileSkip = () => {
    goToStep('advanced')
  }

  const handleAdvancedNext = () => {
    goToStep('email')
  }

  const handleAdvancedSkip = () => {
    goToStep('email')
  }

  const handleGenerateProtocol = async () => {
    try {
      goToStep('loading')
      dispatch({ type: 'SET_ERROR', payload: '' })

      const response = await fetch('/api/generate-protocol', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(state.formData),
      })

      if (!response.ok) {
        throw new Error('Failed to generate protocol')
      }

      const protocol: ProtocolResult = await response.json()
      dispatch({ type: 'SET_PROTOCOL', payload: protocol })

      // Simulate a minimum loading time for better UX
      await new Promise((resolve) => setTimeout(resolve, 2000))

      goToStep('results')
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : 'Unknown error occurred'
      dispatch({ type: 'SET_ERROR', payload: errorMessage })
      goToStep('email')
    }
  }

  const handleReset = () => {
    dispatch({ type: 'RESET' })
    setConsentGiven(false)
  }

  const handleBack = () => {
    const steps: WizardStep[] = ['disclaimer', 'goals', 'profile', 'advanced', 'email']
    const currentIndex = steps.indexOf(state.currentStep)
    if (currentIndex > 0) {
      goToStep(steps[currentIndex - 1])
    }
  }

  return (
    <div className="max-w-3xl mx-auto">
      {/* Progress Bar */}
      {state.currentStep !== 'disclaimer' && state.currentStep !== 'loading' && state.currentStep !== 'results' && (
        <div className="mb-8">
          <div className="flex justify-between mb-2">
            <span className="text-xs font-medium text-warm-700">
              Step {currentStepIndex} of {totalSteps}
            </span>
          </div>
          <div className="h-2 bg-warm-200 rounded-full overflow-hidden">
            <div
              className="h-full bg-sage-600 transition-all duration-300"
              style={{
                width: `${((currentStepIndex) / totalSteps) * 100}%`,
              }}
            />
          </div>
        </div>
      )}

      {/* Steps */}
      {state.currentStep === 'disclaimer' && (
        <DisclaimerStep onNext={handleDisclaimerNext} />
      )}

      {state.currentStep === 'goals' && (
        <GoalsStep
          goals={state.formData.goals}
          onUpdate={(goals) => dispatch({ type: 'UPDATE_FORM', payload: { goals } })}
          onNext={handleGoalsNext}
        />
      )}

      {state.currentStep === 'profile' && (
        <ProfileStep
          formData={state.formData}
          onUpdate={(data) => dispatch({ type: 'UPDATE_FORM', payload: data })}
          onNext={handleProfileNext}
          onSkip={handleProfileSkip}
        />
      )}

      {state.currentStep === 'advanced' && (
        <AdvancedStep
          formData={state.formData}
          onUpdate={(data) => dispatch({ type: 'UPDATE_FORM', payload: data })}
          onNext={handleAdvancedNext}
          onSkip={handleAdvancedSkip}
        />
      )}

      {state.currentStep === 'email' && (
        <EmailStep
          formData={state.formData}
          onUpdate={(data) => dispatch({ type: 'UPDATE_FORM', payload: data })}
          onNext={handleAdvancedNext}
          onGenerate={handleGenerateProtocol}
          isLoading={false}
        />
      )}

      {state.currentStep === 'loading' && <LoadingStep />}

      {state.currentStep === 'results' && state.protocol && (
        <ResultsStep
          protocol={state.protocol}
          email={state.formData.email || ''}
          onReset={handleReset}
        />
      )}

      {/* Error Message */}
      {state.error && (
        <div className="mt-6 p-4 rounded-lg bg-red-50 border border-red-200 text-red-700 text-sm">
          {state.error}
        </div>
      )}

      {/* Navigation */}
      {state.currentStep !== 'disclaimer' && state.currentStep !== 'loading' && state.currentStep !== 'results' && (
        <div className="mt-8 flex gap-3">
          <button
            onClick={handleBack}
            className="btn-secondary inline-flex items-center gap-2"
          >
            <ChevronLeft size={16} />
            Back
          </button>
        </div>
      )}
    </div>
  )
}
